const allbuttons = [
    {
        key:1,
      type: "number",
      name: 0,
      value: 0,
      handle: "handleNumberClick",
    },
    {
        key:2,
      type: "number",
      name: 1,
      value: 1,
      handle: "handleNumberClick",
    },
    {
        key:3,
      type: "number",
      name: 2,
      value: 2,
      handle: "handleNumberClick",
    },
    {
        key:4,
      type: "number",
      name: 3,
      value: 3,
      handle: "handleNumberClick",
    },
    {
        key:5,
      type: "number",
      name: 4,
      value: 4,
      handle: "handleNumberClick",
    },
    { key:6,
      type: "number",
      name: 5,
      value: 5,
      handle: "handleNumberClick",
    },
    {
        key:7,
      type: "number",
      name: 6,
      value: 6,
      handle: "handleNumberClick",
    },
    {
        key:8,
      type: "number",
      name: 7,
      value: 7,
      handle: "handleNumberClick",
    },
    {
        key:9,
      type: "number",
      name: 8,
      value: 8,
      handle: "handleNumberClick",
    },
    {
        key:10,
      type: "number",
      name: 9,
      value: 9,
      handle: "handleNumberClick",
    },
    {
        key:11,
      type: "action",
      name: "+",
      value: "+",
      handle: "handleActionClick",
    },
    {
        key:12,
      type: "action",
      name: "-",
      value: "-",
      handle: "handleActionClick",
    },
    {
        key:13,
      type: "action",
      name: "x",
      value: "*",
      handle: "handleActionClick",
    },
    {
        key:14,
      type: "action",
      name: "/",
      value: "/",
      handle: "handleActionClick",
    },
    {
        key:15,
      type: "action",
      name: ".",
      value: ".",
      handle: "handleActionClick",
    },
    {
        key:16,
      type: "action",
      name: "=",
      value: "=",
      handle: "handleActionClick",
    },
    {
        key:17,
      type: "action",
      name: "+/-",
      value: "+/-",
      handle: "handleActionClick",
    },
    {
        key:18,
      type: "action",
      name: "Del",
      value: "Del",
      handle: "handleActionClick",
    },
    {
        key:19,
      type: "action",
      name: "AC",
      value: "AC",
      handle: "handleActionClick",
    },
    {
      key:20,
      type:"history",
      name:"history",
      value:"history"
    }
  ];
  export default allbuttons;